### ISSUE TITLE
Shared libraries

### ISSUE THREAD

**Issue by dpo** [abelsiqueira/CUTEst.jl#5]
Hi,

First of all, great job with the Julia interface! This will be very useful. As I was saying in another thread, I find Homebrew makes it far easier for Linux and OSX users to install `archdefs`, `sifdecode`, `cutest` and `mastsif` without any hassle. This morning, after seeing your message, I improved the Homebrew formulas to build shared libraries (that was much needed!).

Just to check, I wrote [this quick interface](https://gist.github.com/3a4df27565ef7a753025) and it seems to be working, at least on OSX.

So perhaps the best is to direct users to use Homebrew (and Linuxbrew). The installation instructions are [here](https://github.com/dpo/homebrew-cutest) and are very simple.

**Comment by abelsiqueira** [comment]
Thank you very much for the support. I just commited the homebrew information.
